[2025-01-07T11:25:22.294+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FoReport_file_processing.etl_merge_FO manual__2025-01-07T11:24:53.367669+00:00 [queued]>
[2025-01-07T11:25:22.302+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FoReport_file_processing.etl_merge_FO manual__2025-01-07T11:24:53.367669+00:00 [queued]>
[2025-01-07T11:25:22.302+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-01-07T11:25:22.321+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_merge_FO> on 2025-01-07 11:24:53.367669+00:00
[2025-01-07T11:25:22.341+0000] {standard_task_runner.py:57} INFO - Started process 3018 to run task
[2025-01-07T11:25:22.346+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'FoReport_file_processing', 'etl_merge_FO', 'manual__2025-01-07T11:24:53.367669+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/FoReport_file_processing.py', '--cfg-path', '/tmp/tmpgip82mdv']
[2025-01-07T11:25:22.347+0000] {standard_task_runner.py:85} INFO - Job 542: Subtask etl_merge_FO
[2025-01-07T11:25:22.421+0000] {task_command.py:410} INFO - Running <TaskInstance: FoReport_file_processing.etl_merge_FO manual__2025-01-07T11:24:53.367669+00:00 [running]> on host 8fff7f1050bf
[2025-01-07T11:25:22.505+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FoReport_file_processing' AIRFLOW_CTX_TASK_ID='etl_merge_FO' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T11:24:53.367669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T11:24:53.367669+00:00'
[2025-01-07T11:25:27.748+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FoReport_file_processing.py", line 163, in etl_merge_FO
    merged_collection.insert_many(merged_df.to_dict(orient="records"))
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/collection.py", line 742, in insert_many
    blk.execute(write_concern, session, _Op.INSERT)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/bulk.py", line 595, in execute
    return self.execute_command(generator, write_concern, session, operation)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/bulk.py", line 462, in execute_command
    _raise_bulk_write_error(full_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/bulk.py", line 165, in _raise_bulk_write_error
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': "E11000 duplicate key error collection: Pulang2.foReport_merged_ih&fo index: _id_ dup key: { _id: ObjectId('677d0d39bfe1c97d75d16653') }", 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('677d0d39bfe1c97d75d16653')}, 'op': {'_id': ObjectId('677d0d39bfe1c97d75d16653'), 'Name': 'ANDIKA PUTRA PS', 'Arrival': '2024-01-07T00:00:00.000', 'Depart': '2024-01-10T00:00:00.000', 'Room_Number': '06A07', 'In_House_Date': '2024-01-07T00:00:00.000', 'Room_Type': 'DTMT', 'Arrangement': 'RB', 'Guest_No': 245, 'Age': 37.0, 'Local Region': 'SMG - Semarang', 'Room_Rate': 725000.0, 'Lodging': '        491,735.54', 'Breakfast': '        107,438.02', 'Bill_Number': 383, 'Pay_Article': None, 'Res_No': 359, 'Adult': 2, 'Child': 0, 'Nat': 'IDN', 'Company_TA': 'PLN,  ', 'SOB': 'RSV by Phone', 'Night': 3, 'CI_Time': '16:18', 'CO_Time': '10:46', 'Segment': 'COR-FIT', 'Created': '2024-01-04T00:00:00.000', 'By': '03', 'remarks': 'null ', 'visitor_number': 2, 'visitor_category': 'family/group', 'PURPOSE OF STAY': nan, 'ESCORT': nan, 'FEEDBACK/COMMENT': nan, 'REQUEST': nan}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}
[2025-01-07T11:25:27.795+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=FoReport_file_processing, task_id=etl_merge_FO, execution_date=20250107T112453, start_date=20250107T112522, end_date=20250107T112527
[2025-01-07T11:25:27.839+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 542 for task etl_merge_FO (batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': "E11000 duplicate key error collection: Pulang2.foReport_merged_ih&fo index: _id_ dup key: { _id: ObjectId('677d0d39bfe1c97d75d16653') }", 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('677d0d39bfe1c97d75d16653')}, 'op': {'_id': ObjectId('677d0d39bfe1c97d75d16653'), 'Name': 'ANDIKA PUTRA PS', 'Arrival': '2024-01-07T00:00:00.000', 'Depart': '2024-01-10T00:00:00.000', 'Room_Number': '06A07', 'In_House_Date': '2024-01-07T00:00:00.000', 'Room_Type': 'DTMT', 'Arrangement': 'RB', 'Guest_No': 245, 'Age': 37.0, 'Local Region': 'SMG - Semarang', 'Room_Rate': 725000.0, 'Lodging': '        491,735.54', 'Breakfast': '        107,438.02', 'Bill_Number': 383, 'Pay_Article': None, 'Res_No': 359, 'Adult': 2, 'Child': 0, 'Nat': 'IDN', 'Company_TA': 'PLN,  ', 'SOB': 'RSV by Phone', 'Night': 3, 'CI_Time': '16:18', 'CO_Time': '10:46', 'Segment': 'COR-FIT', 'Created': '2024-01-04T00:00:00.000', 'By': '03', 'remarks': 'null ', 'visitor_number': 2, 'visitor_category': 'family/group', 'PURPOSE OF STAY': nan, 'ESCORT': nan, 'FEEDBACK/COMMENT': nan, 'REQUEST': nan}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}; 3018)
[2025-01-07T11:25:27.934+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-07T11:25:27.975+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
