[2024-12-04T14:34:19.917+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FoReport_file_processing.etl_merge_FO manual__2024-12-04T14:27:16.077404+00:00 [queued]>
[2024-12-04T14:34:20.069+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FoReport_file_processing.etl_merge_FO manual__2024-12-04T14:27:16.077404+00:00 [queued]>
[2024-12-04T14:34:20.072+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-04T14:34:20.251+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_merge_FO> on 2024-12-04 14:27:16.077404+00:00
[2024-12-04T14:34:20.326+0000] {standard_task_runner.py:57} INFO - Started process 359 to run task
[2024-12-04T14:34:20.482+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'FoReport_file_processing', 'etl_merge_FO', 'manual__2024-12-04T14:27:16.077404+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/FoReport_file_processing.py', '--cfg-path', '/tmp/tmpeumlbpf9']
[2024-12-04T14:34:20.502+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask etl_merge_FO
[2024-12-04T14:34:21.196+0000] {task_command.py:410} INFO - Running <TaskInstance: FoReport_file_processing.etl_merge_FO manual__2024-12-04T14:27:16.077404+00:00 [running]> on host effe9442f8f2
[2024-12-04T14:34:22.005+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FoReport_file_processing' AIRFLOW_CTX_TASK_ID='etl_merge_FO' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T14:27:16.077404+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T14:27:16.077404+00:00'
[2024-12-04T14:34:41.021+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FoReport_file_processing.py", line 159, in etl_merge_FO
    merged_collection.insert_many(merged_df.to_dict(orient="records"))
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/collection.py", line 742, in insert_many
    blk.execute(write_concern, session, _Op.INSERT)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/bulk.py", line 595, in execute
    return self.execute_command(generator, write_concern, session, operation)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/bulk.py", line 462, in execute_command
    _raise_bulk_write_error(full_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/bulk.py", line 165, in _raise_bulk_write_error
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': "E11000 duplicate key error collection: Pulang2.etl_FO_data index: _id_ dup key: { _id: ObjectId('674f2fc318f753c09ffe9395') }", 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('674f2fc318f753c09ffe9395')}, 'op': {'_id': ObjectId('674f2fc318f753c09ffe9395'), 'Name': 'ALEXANDRE KANDOU', 'Arrival': '2024-02-05T00:00:00.000', 'Depart': '2024-02-06T00:00:00.000', 'Room_Number': '17B06R', 'In_House_Date': '05 February 2024', 'Room_Type': 'DKCK', 'Arrangement': 'RB', 'Guest_No': 1172, 'Age': 47.0, 'Local Region': 'JKT - Jakarta', 'Room_Rate': 620644.0, 'Lodging': '        405,490.91', 'Breakfast': '        107,438.02', 'Bill_Number': 1368, 'Pay_Article': None, 'Res_No': 1206, 'Adult': 2, 'Child': 0, 'Nat': 'IDN', 'Company_TA': 'AGODA,  T&T', 'SOB': 'OTA', 'Night': 1, 'CI_Time': '22:25', 'CO_Time': '10:39', 'Segment': 'OTA', 'Created': '31 January 2024', 'By': '**', 'remarks': 'NonSmoke LargeBed ', 'visitor_number': 2, 'visitor_category': 'family/group', 'PURPOSE OF STAY': nan, 'ESCORT': nan, 'FEEDBACK/COMMENT': nan, 'REQUEST': nan}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}
[2024-12-04T14:34:41.239+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=FoReport_file_processing, task_id=etl_merge_FO, execution_date=20241204T142716, start_date=20241204T143419, end_date=20241204T143441
[2024-12-04T14:34:41.426+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 62 for task etl_merge_FO (batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': "E11000 duplicate key error collection: Pulang2.etl_FO_data index: _id_ dup key: { _id: ObjectId('674f2fc318f753c09ffe9395') }", 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('674f2fc318f753c09ffe9395')}, 'op': {'_id': ObjectId('674f2fc318f753c09ffe9395'), 'Name': 'ALEXANDRE KANDOU', 'Arrival': '2024-02-05T00:00:00.000', 'Depart': '2024-02-06T00:00:00.000', 'Room_Number': '17B06R', 'In_House_Date': '05 February 2024', 'Room_Type': 'DKCK', 'Arrangement': 'RB', 'Guest_No': 1172, 'Age': 47.0, 'Local Region': 'JKT - Jakarta', 'Room_Rate': 620644.0, 'Lodging': '        405,490.91', 'Breakfast': '        107,438.02', 'Bill_Number': 1368, 'Pay_Article': None, 'Res_No': 1206, 'Adult': 2, 'Child': 0, 'Nat': 'IDN', 'Company_TA': 'AGODA,  T&T', 'SOB': 'OTA', 'Night': 1, 'CI_Time': '22:25', 'CO_Time': '10:39', 'Segment': 'OTA', 'Created': '31 January 2024', 'By': '**', 'remarks': 'NonSmoke LargeBed ', 'visitor_number': 2, 'visitor_category': 'family/group', 'PURPOSE OF STAY': nan, 'ESCORT': nan, 'FEEDBACK/COMMENT': nan, 'REQUEST': nan}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}; 359)
[2024-12-04T14:34:41.583+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-04T14:34:41.900+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
